name: Build Executables

on:
  push:
    branches:
      - feat_shop

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyarmor
          pip install -r requirements.txt

      - name: Install UPX
        run: |
          choco install upx

      - name: Build EXE
        run: |
          pyarmor gen wuneng.py
          pyinstaller wuneng.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: wuneng-windows
          path: dist/wuneng.exe

  build-macos-arm64:
    runs-on: macos-latest
    needs: [build-windows]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyarmor
          pip install -r requirements.txt

      - name: Install UPX
        run: |
          brew install upx

      - name: Build MacOS ARM executable
        run: |
          pyarmor gen wuneng.py
          pyinstaller wuneng.spec

      - name: Upload MacOS ARM artifact
        uses: actions/upload-artifact@v4
        with:
          name: wuneng-macos-arm64
          path: dist/wuneng

  build-linux:
    runs-on: ubuntu-22.04
    needs: [build-windows]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyarmor
          pip install -r requirements.txt

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Build Linux executable
        run: |
          pyarmor gen wuneng.py
          pyinstaller wuneng.spec

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: wuneng-linux
          path: dist/wuneng

  build-macos-intel:
    runs-on: macos-latest
    needs: [build-windows]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          arch -x86_64 pip3 install --upgrade pip
          arch -x86_64 pip3 install pyinstaller
          arch -x86_64 pip3 install -r requirements.txt

      - name: Install UPX
        run: |
          brew install upx

      - name: Build MacOS Intel executable
        env:
          TARGET_ARCH: 'x86_64'
        run: |
          arch -x86_64 pyinstaller wuneng2.spec

      - name: Upload MacOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wuneng-macos-intel
          path: dist/wuneng